export const nodes = [ 
  {id : '0', label : 'Cisco', level : 0, width : 150, length : 1000},

  { id: '1', label: 'Networking', level: 1, width: 150, length: 50 }, 
  { id: '7', label: 'Security', level: 1, width: 150, length: 50 }, 
  { id: '30', label: 'Collaboration', level: 1, width: 150, length: 50 }, 
  { id: '36', label: 'Application Performance', level: 1, width: 150, length: 50 }, 

  { id: '2', label: 'Cisco Secure Firewall ASA', level: 2, width: 150, length: 50 }, 
  { id: '5', label: 'Cisco Catalyst Switches', level: 2, width: 150, length: 50 }, 
  { id: '8', label: 'Cisco Secure Web Appliance', level: 2, width: 150, length: 50 }, 
  { id: '14', label: 'Cisco Identity Services Engine', level: 2, width: 150, length: 50 }, 
  { id: '17', label: 'Cisco Secure Email Gateway', level: 2, width: 150, length: 50 }, 
  { id: '20', label: 'Cisco Umbrella', level: 2, width: 150, length: 50 }, 
  { id: '22', label: 'Cisco Umbrella Investigate', level: 2, width: 150, length: 50 }, 
  { id: '24', label: 'Cisco Threat Response', level: 2, width: 150, length: 50 }, 
  { id: '26', label: 'Cisco Secure Firewall', level: 2, width: 150, length: 50 }, 
  { id: '28', label: 'Cisco Tetration Platform', level: 2, width: 150, length: 50 }, 
  { id: '31', label: 'Cisco Webex', level: 2, width: 150, length: 50 }, 
  { id: '35', label: 'Cisco Spark Connector', level: 3, width: 150, length: 50 }, 
  { id: '37', label: 'Cisco AppDynamics', level: 2, width: 150, length: 50 }, 

  { id: '3', label: 'Splunk Add-on for Cisco Meraki', level: 3, width: 150, length: 50 }, 
  { id: '4', label: 'Cisco Meraki Dashboard Connector', level: 3, width: 150, length: 50 },   
  { id: '6', label: 'Cisco Catalyst Connector', level: 3, width: 150, length: 50 }, 
  { id: '9', label: 'Splunk Add-on for Cisco WSA', level: 3, width: 150, length: 50 }, 
  { id: '10', label: 'Cisco Secure Firewall ASA', level: 3, width: 150, length: 50 }, 
  { id: '11', label: 'Splunk Add-on for Cisco ASA', level: 3, width: 150, length: 50 }, 
  { id: '12', label: 'Cisco ASA Connector', level: 3, width: 150, length: 50 }, 
  { id: '13', label: 'Cisco Firepower Connector', level: 3, width: 150, length: 50 }, 
  {id: '15', label: 'Splunk Add-on for Cisco Identity Services', level: 3, width: 150, length: 50 }, 
  { id: '16', label: 'Cisco ISE Connector', level: 3, width: 150, length: 50 }, 
  { id: '18', label: 'Splunk Add-on for Cisco ESA', level: 3, width: 150, length: 50 }, 
  { id: '19', label: 'Cisco ESA Connector', level: 3, width: 150, length: 50 }, 
  { id: '21', label: 'Cisco Umbrella Connector', level: 3, width: 150, length: 50 }, 
  { id: '23', label: 'Cisco Umbrella Investigate Connector', level: 3, width: 150, length: 50 }, 
  { id: '25', label: 'Cisco Threat Response Connector', level: 3, width: 150, length: 50 }, 
  { id: '27', label: 'Cisco Secure Firewall Connector', level: 3, width: 150, length: 50 },
  { id: '29', label: 'Cisco Tetration Analytics Connector', level: 3, width: 150, length: 50 }, 
  { id: '32', label: 'Cisco Webex Meetings Add-on for Splunk', level: 3, width: 150, length: 50 }, 
  { id: '33', label: 'Cisco Webex Connector', level: 3, width: 150, length: 50 },
  { id: '34', label: 'Cisco Spark', level: 3, width: 150, length: 50 },   
  { id: '38', label: 'Splunk Add-on for AppDynamics', level: 3, width: 150, length: 50 } ,

  {id : '39', label : 'Splunk Cloud', level : 4, width : 150, length : 50},
  {id : '40', label : 'SOAR', level : 4, width : 150, length : 50},

  {id : '41', label : 'Splunk', level : 5, width : 150, length : 1000},
];

export const links =  [
    // Level 1 to Level 2 links
    { source: '1', target: '2' },
    { source: '1', target: '5' },
    { source: '7', target: '8' },
    { source: '7', target: '2' },
    { source: '7', target: '14' },
    { source: '7', target: '17' },
    { source: '7', target: '20' },
    { source: '7', target: '22' },
    { source: '7', target: '24' },
    { source: '7', target: '26' },
    { source: '7', target: '28' },
    { source: '30', target: '31' },
    { source: '37', target: '38'},
    { source: '30', target: '34'},
  
    // Level 3 to Level 4 links
    { source: '3', target: '39' },
    { source: '4', target: '40' },
    { source: '6', target: '40' },
    { source: '9', target: '39' },
    { source: '10', target: '40' },
    { source: '11', target: '39' },
    { source: '12', target: '40' },
    { source: '13', target: '40' },
    { source: '15', target: '39' },
    { source: '16', target: '40' },
    { source: '18', target: '39' },
    { source: '19', target: '40' },
    { source: '21', target: '40' },
    { source: '23', target: '40' },
    { source: '25', target: '40' },
    { source: '27', target: '40' },
    { source: '29', target: '40' },
    { source: '32', target: '39' },
    { source: '33', target: '40' },
    { source: '34', target: '40' },
    { source: '38', target: '39' },

    

    // Level 2 to Level 3 links
    { source: '2', target: '3' },
    { source: '2', target: '4' },
    { source: '5', target: '6' },
    { source: '8', target: '9' },
    { source: '2', target: '10' },
    { source: '2', target: '11' },
    { source: '14', target: '15' },
    { source: '14', target: '16' },
    { source: '17', target: '18' },
    { source: '17', target: '19' },
    { source: '20', target: '21' },
    { source: '22', target: '23' },
    { source: '24', target: '25' },
    { source: '26', target: '27' },
    { source: '28', target: '29' },
    { source: '31', target: '32' },
    { source: '31', target: '33' },
    { source: '34', target: '35' },
    { source: '37', target: '38' }
  ];
