name: Validate JSON
on: 
  pull_request:
  push:
    branches:
      - "test-workflow"
    paths:
      - data.json
jobs: 
  validate-json: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/workflows/validate-json.yml
          INPUT_JSONS: /public/data.json
