name: Validate JSON
on: 
  pull_request:
  push:
    branches:
      - "test-workflow"
    paths:
      - data.json
jobs: 
  validate-json: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
